name: school18
channels:
  - anaconda
dependencies:
  - python=3.6
  - astropy
  - cython
  - h5py
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pytables
  - pillow
  - seaborn
